const url = '/gallery/'

export const logosData=[
    {
        id:1,
        url:`${url}алибра.png`,
        alt:"алибра"
    },
    {
        id:2,
        url:`${url}гапресурс.png`,
        alt:"гапресурс"
    },
    {
        id:3,
        url:`${url}алиэкспресс.png`,
        alt:"алиэкспресс"
    },
    {
        id:4,
        url:`${url}джак.png`,
        alt:"джак"
    },
    {
        id:5,
        url:`${url}колди.png`,
        alt:"колди"
    },
        {
        id:6,
        url:`${url}ланит.png`,
        alt:"ланит"
    },
    {
        id:7,
        url:`${url}легранд.png`,
        alt:"легранд"
    },
    {
        id:8,
        url:`${url}лукойл.png`,
        alt:"лукойл"
    },
    {
        id:9,
        url:`${url}ортолайк.png`,
        alt:"ортолайк"
    },
    {
        id:10,
        url:`${url}помидорка.png`,
        alt:"помидорка"
    },
        {
        id:11,
        url:`${url}пфайзер.png`,
        alt:"пфайзер"
    },
    {
        id:12,
        url:`${url}северсталь.png`,
        alt:"северсталь"
    },
    {
        id:13,
        url:`${url}сенсой.png`,
        alt:"сенсой"
    },
    {
        id:14,
        url:`${url}сентисс фарма.png`,
        alt:"сентисс фарма"
    },
    {
        id:15,
        url:`${url}сибур.png`,
        alt:"сибур"
    },
    {
        id:16,
        url:`${url}славянка.png`,
        alt:"славянка"
    },
        {
        id:17,
        url:`${url}сотекс.png`,
        alt:"сотекс"
    },
    {
        id:18,
        url:`${url}ташир.png`,
        alt:"ташир"
    },
    {
        id:19,
        url:`${url}терволина.png`,
        alt:"терволина"
    },
    {
        id:20,
        url:`${url}эталон.png`,
        alt:"эталон"
    },
    {
        id:15,
        url:`${url}ювона.png`,
        alt:"ювона"
    }
]